name: weekly-compliance
on:
  schedule:
    - cron: '0 15 * * 1'
  workflow_dispatch:
    

jobs:
  issue_maker:
    name: Issue maker
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          stable: 'true'

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: letsencrypt/sre-tools
          ref: compliance-tracker

      - name: Run Compliance Tracker
        id: compliance
        run: 'echo "::set-output name=issue::$(go run cmd/compliance-tracker/main.go)"'

      - name: Print output
        run: 'echo ${{ steps.compliance.outputs.issue}}'
      

