name: weekly-compliance
on:
  schedule:
    - cron: '0 15 * * 1'
  workflow_dispatch:
    

jobs:
  issue_maker:
    name: Issue maker
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: letsencrypt/sre-tools
          ref: compliance-tracker

      - name: Run Compliance Tracker
        id: compliance
        run: ISSUE="$(go run cmd/compliance-tracker/main.go)"" && echo ::set-output name=ISSUE::"$ISSUE"

      - name: Print output
        run: 'echo ${{ steps.compliance.outputs.ISSUE}}'
      
      - name: Create issue 
        uses: imjohnbo/issue-bot@v3.0
        with:
          labels: "weekly"
          title: "Weekly compliance tracker"
          body: ${{ steps.compliance.outputs.issue }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
